from __future__ import annotations

import argparse
import sys
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
AI_SERVICE_DIR = SCRIPT_DIR.parent
if str(AI_SERVICE_DIR) not in sys.path:
    sys.path.insert(0, str(AI_SERVICE_DIR))

from app.rag.evaluators.testset_generation import (
    ReviewImportValidationError,
    build_reviewed_import_payload,
    write_reviewed_import_json,
)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Merge an automatically generated RAGAS draft JSON with a human-reviewed CSV, "
            "then produce a Spring Boot /api/rag/evaluation-cases/import payload."
        ),
    )
    parser.add_argument("--draft-json", required=True, help="Draft JSON generated by generate_ragas_testset_draft.py.")
    parser.add_argument("--review-csv", required=True, help="Human-reviewed UTF-8 BOM CSV.")
    parser.add_argument("--experiment-id", required=True, help="Target Spring Boot RAG experiment UUID.")
    parser.add_argument("--output-json", required=True, help="Destination import payload JSON.")
    parser.add_argument(
        "--active-only",
        action="store_true",
        help="Only include cases whose humanDecision/status maps to ACTIVE.",
    )
    parser.add_argument(
        "--exclude-rejected",
        action="store_true",
        help="Skip REJECTED cases instead of importing them as rejected records.",
    )
    args = parser.parse_args()

    try:
        result = build_reviewed_import_payload(
            draft_json_path=args.draft_json,
            review_csv_path=args.review_csv,
            experiment_id=args.experiment_id,
            active_only=args.active_only,
            include_rejected=not args.exclude_rejected,
        )
    except ReviewImportValidationError as exc:
        for warning in exc.warnings:
            print("warning: " + warning, file=sys.stderr)
        for error in exc.errors:
            print("error: " + error, file=sys.stderr)
        return 2

    write_reviewed_import_json(result, args.output_json)

    counts = ", ".join(f"{key}={value}" for key, value in result.counts.items() if value)
    print(
        f"finalized {len(result.payload['items'])} evaluation cases; "
        f"output={args.output_json}; counts={counts or 'none'}"
    )
    if result.skipped_case_ids:
        print("skipped caseIds=" + ",".join(result.skipped_case_ids))
    for warning in result.warnings:
        print("warning: " + warning)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
